### PR TITLE
Fix: correct yhat to hat{y}

### PR DESCRIPTION
**Pull request by amanmdesai**

### CODE REVIEW

**Comment by tompollard** [comment]
looks good, thanks!

**Comment by tompollard** [comment]
My bad, I should have checked more carefully! It looks like the schedule at https://carpentries-incubator.github.io/machine-learning-novice-python/ isn't rendering the section correctly:

Screen Shot 2022-08-01 at 11 00 26 AM

**Comment by tompollard** [comment]
I've reverted the commit for now, but would welcome another pull request. Will do a better job at testing next time!

**Comment by amanmdesai** [comment]
Sure I will open another pull request. Thanks.

**Comment by amanmdesai** [comment]
Hi @tompollard, just now I tried to test "yhat to \hat{y}" on my fork (also tried some different variants with $, $$ ..). 
But it seems that I am unable to make the page work.  I do not know why is that a problem.

**Comment by tobyhodges** [comment]
@amanmdesai perhaps you have already tried this, but I think the problem might be solved by adding a second backslash `\` i.e. `$y$ is a known target. $\\hat{y}$ ($y hat$) is a prediction.`

**Comment by amanmdesai** [comment]
Thanks a lot @tobyhodges. 
Many thanks for the suggestion. It works! I will open a new pull request.

**Comment by tompollard** [comment]
thanks @tobyhodges and @amanmdesai!

**Comment by tobyhodges** [comment]
Glad to hear it, @amanmdesai! It has something to do with how the LaTeX syntax is parsed within the YAML header - in this case the backslash needs to be 'escaped' with an additional backslash, to make sure it gets passed as a backslash to the Jekyll engine when it processes the Markdown in and formats it as HTML in the resulting webpage.

**Comment by amanmdesai** [comment]
> Glad to hear it, @amanmdesai! It has something to do with how the LaTeX syntax is parsed within the YAML header - in this case the backslash needs to be 'escaped' with an additional backslash, to make sure it gets passed as a backslash to the Jekyll engine when it processes the Markdown in and formats it as HTML in the resulting webpage.

Thanks @tobyhodges. This is really helpful.
I will keep this in mind.

**Pull request merged**
